### Variables

#### local 
@base_url = http://127.0.0.1:8000


### 강의 가져오기 ###
POST {{base_url}}/course-evaluation/test
Content-Type: application/json

{ 
  "course_code": "",
  "course_name": "화학",
  "course_professor": "",
  "course_semester": "20-1"
}




