# Generated by Django 3.0.3 on 2020-02-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('codeNum', models.CharField(max_length=20)),
                ('text', models.TextField()),
            ],
        ),
    ]
