# Generated by Django 3.0.3 on 2020-02-17 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='text',
        ),
    ]
