# Generated by Django 3.0.3 on 2020-02-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fia', '0003_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='star',
            field=models.IntegerField(default=5),
        ),
    ]
