# Generated by Django 3.0.3 on 2020-02-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fia', '0006_evaluation_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('course_number', models.IntegerField()),
                ('course_name', models.CharField(max_length=30)),
                ('course_professor', models.CharField(max_length=30)),
                ('course_semester', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
