# Generated by Django 3.0.3 on 2020-02-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fia', '0007_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_semester',
            field=models.CharField(max_length=10),
        ),
    ]
