# Generated by Django 3.0.3 on 2020-02-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fia', '0008_auto_20200220_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_number',
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default=str, max_length=15),
            preserve_default=False,
        ),
    ]
