# Generated by Django 3.0.3 on 2020-02-20 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fia', '0009_auto_20200220_0237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='created_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='modified_time',
            new_name='updated_at',
        ),
    ]
