# Generated by Django 3.0.3 on 2020-02-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fia', '0010_auto_20200220_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='password',
            field=models.IntegerField(default=0),
        ),
    ]
