# Generated by Django 3.0.3 on 2020-02-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fia', '0011_auto_20200220_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='subject',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
