# Generated by Django 3.0.3 on 2020-02-20 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fia', '0011_auto_20200220_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequestComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('target_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='fia.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='fia.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
