# Generated by Django 3.0.3 on 2020-02-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fia', '0012_lecture_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='subject',
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
