# Generated by Django 3.0.3 on 2020-02-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fia', '0012_userrequestcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRequestComment',
        ),
    ]
