# Generated by Django 3.0.3 on 2020-02-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fia', '0013_auto_20200222_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
    ]
