# Generated by Django 3.0.3 on 2020-02-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fia', '0014_remove_course_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_professor',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_semester',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
